name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: mfigurski80
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build the Docker image
      run: docker build -t mfigurski80/cyd-whois:$(date +%s) -t mfigurski80/cyd-whois:latest .
      
    - name: Push to Dockerhub Registry
      run: docker push -a mfigurski80/cyd-whois
